"""Generate LaTeX tables from the committed results CSVs (no experiment is rerun).

    python latex/tools/make_tables.py

Main-text tables go to latex/tables/*.tex, the full record to latex/tables/appendix/*.tex.
Numbers are only rounded, never recomputed, except where noted (E1 ranges are min/max of the
certification CSV; the E12b/E12 subsets are row selections of the summary CSVs).
"""

from __future__ import annotations

import math
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
RES = ROOT / "results"
OUT = ROOT / "latex" / "tables"
APP = OUT / "appendix"


def esc(s) -> str:
    s = str(s)
    for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("#", r"\#"), ("_", r"\_"),
                 ("{", r"\{"), ("}", r"\}"), ("$", r"\$")):
        s = s.replace(a, b)
    return s


def num(v, d=3) -> str:
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return "--"
    if isinstance(v, (bool,)):
        return "yes" if v else "no"
    if isinstance(v, (int,)) or (isinstance(v, float) and float(v).is_integer() and abs(v) >= 10):
        return f"{int(v):,}".replace(",", "{,}")
    v = float(v)
    if v != 0 and (abs(v) < 10 ** (-d) or abs(v) >= 1e5):
        m, e = f"{v:.2e}".split("e")
        return f"${m}\\times10^{{{int(e)}}}$"
    return f"{v:.{d}f}"


def cell(v, d=3):
    if isinstance(v, str):
        return esc(v)
    return num(v, d)


def tabular(df: pd.DataFrame, cols, heads, align=None, d=3, long=False, caption=None, label=None,
            size=r"\footnotesize", star=False) -> str:
    align = align or ("l" + "r" * (len(cols) - 1))
    body = [" & ".join(cell(r[c], d if not isinstance(d, dict) else d.get(c, 3)) for c in cols) + r" \\"
            for _, r in df.iterrows()]
    head = " & ".join(heads) + r" \\"
    if long:
        out = [size, r"\begin{longtable}{" + align + "}"]
        if caption:
            out.append(r"\caption{" + caption + "}" + (r"\label{" + label + "}" if label else "") + r"\\")
        out += [r"\toprule", head, r"\midrule", r"\endfirsthead", r"\toprule", head, r"\midrule", r"\endhead",
                r"\bottomrule", r"\endlastfoot"] + body + [r"\end{longtable}", r"\normalsize"]
        return "\n".join(out) + "\n"
    out = [r"\begin{tabular}{" + align + "}", r"\toprule", head, r"\midrule"] + body + [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(out) + "\n"


def write(path: Path, s: str):
    path.write_text("% generated by latex/tools/make_tables.py from results/ -- do not edit\n" + s)


def main():
    APP.mkdir(parents=True, exist_ok=True)

    # ---------------------------------------------------------------- E1
    e1 = pd.read_csv(RES / "E1_encoding" / "encoding_certification.csv")
    e1["inst"] = e1.instance.str.replace("_eq0", "").str.replace("_eq1", " + equity")
    write(OUT / "e1.tex", tabular(
        e1, ["inst", "n_decision", "n_slack", "milp_opt", "qubo_ground_obj", "match", "safe_penalty", "range_over_safe"],
        ["instance", "dec.", "slack", "MILP opt.\\ (\\degC)", "QUBO ground (\\degC)", "match",
         "$\\Lambda_{\\mathrm{safe}}$", "range/safe"], align="lrrrrcrr", d=3, size=r"\scriptsize"))

    # ---------------------------------------------------------------- E2
    e2 = pd.read_csv(RES / "E2_fidelity" / "fidelity_summary.csv")
    e2["order"] = e2["order"].astype(str)
    piv = e2.pivot(index="decay_length_m", columns="order", values="benefit_lost_pct_mean").reset_index()
    piv = piv.rename(columns={"decay_length_m": "L"})
    piv["L"] = piv["L"].astype(int).astype(str)
    for c in ("1", "2", "2-fit", "3"):
        piv[c] = piv[c].map(lambda v: f"{v:.2f}\\%")
    write(OUT / "e2.tex", tabular(piv, ["L", "1", "2", "2-fit", "3"],
                                   ["$L$ (m)", "additive $K{=}1$", "QUBO $K{=}2$ (Taylor)", "QUBO (LSQ fit)", "HUBO $K{=}3$"],
                                   align="rrrrr"))
    write(APP / "e2_full.tex", tabular(e2.assign(decay_length_m=e2.decay_length_m.astype(str)),
                                        ["decay_length_m", "order", "benefit_lost_pct_mean", "regret_C_mean", "same_plan_frac",
                                         "abs_model_error_C", "terms"],
                                        ["$L$ (m)", "order", "benefit lost (\\%)", "regret (\\degC)", "same plan",
                                         "$|$model err.$|$ (\\degC)", "terms"], long=True,
                                        caption="E2 surrogate fidelity (\\texttt{results/E2\\_fidelity/fidelity\\_summary.csv}).",
                                        label="tab:app-e2", d=4))

    # ---------------------------------------------------------------- E8b
    e8b = pd.read_csv(RES / "E8b_depth" / "summary.csv")
    rows = []
    for m in ("Dicke-XY complete", "Dicke-XY ring", "X-mixer penalty QAOA"):
        g = e8b[e8b.method == m].set_index("p")
        r = {"method": m}
        for p in (1, 2, 3, 4, 6):
            x = g.loc[float(p)]
            r[str(p)] = f"{x.p_opt_mean:.3f}" + (f" [{x.p_opt_min:.2f}--{x.p_opt_max:.2f}]" if m != "X-mixer penalty QAOA" and p in (2, 6) else "")
        rows.append(r)
    t = pd.DataFrame(rows)
    write(OUT / "e8b.tex", tabular(t, ["method", "1", "2", "3", "4", "6"],
                                    ["method", "$p{=}1$", "$p{=}2$", "$p{=}3$", "$p{=}4$", "$p{=}6$"], align="lrrrrr",
                                    size=r"\scriptsize"))
    ref = e8b[e8b.p.isna()]
    write(OUT / "e8b_ref.tex", tabular(ref, ["method", "p_opt_mean", "benefit_true_mean", "wall_time_s_mean"],
                                        ["method", "\\Popt", "benefit", "wall (s)"], d=3))
    write(APP / "e8b_full.tex", tabular(
        e8b.assign(p=e8b.p.map(lambda v: "--" if pd.isna(v) else str(int(v)))),
        ["method", "p", "p_opt_mean", "p_opt_min", "p_opt_max", "p_feasible_mean", "benefit_true_mean", "wall_time_s_mean"],
        ["method", "$p$", "\\Popt{} mean", "min", "max", "P(feas)", "benefit", "wall (s)"], long=True,
        caption="E8b depth curve (\\texttt{results/E8b\\_depth/summary.csv}); mean over 3 cities.", label="tab:app-e8b"))

    # ---------------------------------------------------------------- E12
    e12 = pd.read_csv(RES / "E12_comparable" / "summary.csv")
    h = e12[e12.family == "H"]
    write(OUT / "e12.tex", tabular(h, ["method", "P_feas", "P_opt", "benefit_mean", "benefit_min", "wall_s_mean", "comparable"],
                                    ["method (family H)", "P(feas)", "\\Popt", "benefit", "min", "wall (s)", "comp."],
                                    align="lrrrrrc", size=r"\scriptsize"))
    write(APP / "e12_full.tex", tabular(
        e12, ["method", "family", "n_feasible", "P_feas", "P_opt", "benefit_mean", "benefit_min", "wall_s_mean", "T_star_mean", "comparable"],
        ["method", "fam.", "$|F|$", "P(feas)", "\\Popt", "benefit", "min", "wall (s)", "$T^\\ast$ (s)", "comp."], long=True,
        caption="E12 summary (\\texttt{results/E12\\_comparable/summary.csv}).", label="tab:app-e12", size=r"\scriptsize",
        align="llp{2.2cm}rrrrrrc"))

    # ---------------------------------------------------------------- E12b
    e = pd.read_csv(RES / "E12b_ablation" / "summary.csv")
    e["proposals_M"] = e.proposals / 1e6
    e = e.rename(columns={"w/t/l_vs_FeasibleSA": "wtl"})
    for c in ("comparable_to_feasible_sa", "beats_feasible_sa", "wtl"):
        e[c] = e[c].fillna("--")
    e.loc[e.method == "FeasibleSA", "wtl"] = "--"
    eh = e[e.family == "H"]
    write(OUT / "e12b.tex", tabular(
        eh, ["method", "clock", "P_opt", "benefit_mean", "benefit_min", "wall_s", "proposals_M", "comparable_to_feasible_sa",
             "beats_feasible_sa", "wtl"],
        ["method", "clock", "\\Popt", "benefit", "min", "wall (s)", "prop.\\ (M)", "$\\geq$0.95 FSA", "beats", "w/t/l"],
        align="llrrrrrccc", size=r"\scriptsize", d={"proposals_M": 2, "wall_s": 2}))
    write(OUT / "e12b_eq.tex", tabular(
        eh[(eh.clock == "equal_work") | (eh.clock == "none")],
        ["method", "clock", "P_opt", "benefit_mean", "benefit_min", "wall_s", "proposals_M", "wtl"],
        ["method", "clock", "\\Popt", "benefit", "min", "wall (s)", "prop.\\ (M)", "w/t/l"],
        align="llrrrrrc", size=r"\scriptsize", d={"proposals_M": 2, "wall_s": 2}))
    write(APP / "e12b_full.tex", tabular(
        e, ["method", "clock", "family", "instances", "P_feas", "P_opt", "benefit_mean", "benefit_min", "wall_s", "proposals_M",
            "FeasibleSA_benefit_same_clock_same_instances", "comparable_to_feasible_sa", "beats_feasible_sa", "wtl"],
        ["method", "clock", "fam.", "inst.", "P(feas)", "\\Popt", "benefit", "min", "wall", "prop.\\ (M)", "FSA", "$\\geq$0.95", "beats", "w/t/l"],
        long=True, caption="E12b ablation (\\texttt{results/E12b\\_ablation/summary.csv}).", label="tab:app-e12b",
        size=r"\scriptsize", align="p{2.1cm}llrrrrrrrrccc", d={"proposals_M": 2, "wall_s": 2}))

    # ---------------------------------------------------------------- E13 (typed from results/E13_tile/e13.md)
    e13 = pd.DataFrame([
        ("MILP (HiGHS, 8 s cap)", 1.0, 1.0, 1.0000, 1.6685), ("Greedy planner", 0.0, 0.0, 0.0, 0.0602),
        ("FeasibleSA", 1.0, 0.5, 0.9569, 66.5595), ("Tabu-on-F", 1.0, 0.0, 0.6412, 67.3511),
        ("FeasibleSQA", 1.0, 0.5, 0.9998, 63.7211), ("SA-matched α=0.01 + repair", 1.0, 1.0, 1.0000, 64.6799)],
        columns=["method", "P_feas", "P_opt", "benefit", "wall"])
    write(OUT / "e13.tex", tabular(e13, ["method", "P_feas", "P_opt", "benefit", "wall"],
                                    ["method", "P(feas)", "\\Popt", "benefit", "wall (s)"], d={"benefit": 4, "wall": 2,
                                                                                            "P_feas": 1, "P_opt": 1}))

    # ---------------------------------------------------------------- appendix: the rest
    s3 = pd.read_csv(RES / "E3_scaling" / "scaling_summary.csv")
    write(APP / "e3_full.tex", tabular(
        s3, ["family", "grid", "solver", "n_vars", "p_success", "p_success_pp", "p_feasible", "mean_benefit_ratio",
             "mean_benefit_ratio_pp", "time_per_read_s"],
        ["family", "grid", "solver", "vars", "P(succ)", "pp", "P(feas)", "benefit", "benefit pp", "s/read"],
        long=True, caption="E3 solver scaling, medians over instances $\\times$ seeds (\\texttt{results/E3\\_scaling/scaling\\_summary.csv}).",
        label="tab:app-e3", size=r"\scriptsize", align="lllrrrrrrr"))
    s4 = pd.read_csv(RES / "E4_penalty" / "penalty_summary.csv")
    write(APP / "e4_full.tex", tabular(
        s4, ["instance", "solver", "penalty_mult", "p_feasible", "p_success", "p_success_pp", "mean_benefit_ratio", "mean_benefit_ratio_pp"],
        ["instance", "solver", "$\\Lambda/\\Lambda_{\\mathrm{safe}}$", "P(feas)", "P(succ)", "pp", "benefit", "benefit pp"],
        long=True, caption="E4 penalty sweep (\\texttt{results/E4\\_penalty/penalty\\_summary.csv}).", label="tab:app-e4",
        size=r"\scriptsize", align="llrrrrrr"))
    s5 = pd.read_csv(RES / "E5_hubo" / "hubo_summary.csv")
    write(APP / "e5_full.tex", tabular(
        s5, ["formulation", "solver", "n_vars", "p_success", "p_success_pp", "mean_benefit_ratio", "time_per_read_s"],
        ["formulation", "solver", "vars", "P(opt) raw", "pp", "benefit", "s/read"], long=True,
        caption="E5 native HUBO vs Rosenberg QUBO (\\texttt{results/E5\\_hubo/hubo\\_summary.csv}).", label="tab:app-e5"))
    s8 = pd.read_csv(RES / "E8_mixers" / "summary_by_family.csv")
    write(APP / "e8_full.tex", tabular(
        s8, ["family", "method", "p_opt", "p_feasible", "benefit_true", "wall_time_s"],
        ["family", "method", "\\Popt", "P(feas)", "benefit", "wall (s)"], long=True,
        caption="E8 constraint-preserving mixers by family (\\texttt{results/E8\\_mixers/summary\\_by\\_family.csv}).",
        label="tab:app-e8", size=r"\scriptsize", align="lp{6.2cm}rrrr"))
    s9 = pd.read_csv(RES / "E9_hybrid" / "summary.csv")
    s9["alpha"] = s9["alpha"].map(lambda v: "--" if pd.isna(v) else f"{v:g}")
    write(APP / "e9_full.tex", tabular(
        s9, ["solver", "alpha", "p_feasible", "p_success", "p_success_pp", "mean_benefit_ratio_pp", "time_per_read_s_pp"],
        ["solver", "$\\alpha$", "P(feas)", "P(opt) raw", "P(opt) pp", "benefit pp", "s/read pp"], long=True,
        caption="E9 weak penalty + repair (\\texttt{results/E9\\_hybrid/summary.csv}).", label="tab:app-e9"))
    s10 = pd.read_csv(RES / "E10_penalty_form" / "summary.csv")
    write(APP / "e10_full.tex", tabular(
        s10, ["form", "weight", "n_vars", "dynamic_range", "ground_feasible", "ground_is_optimum", "p_opt", "p_opt_pp"],
        ["form", "weight", "vars", "dyn.\\ range", "ground feas.", "ground opt.", "P(opt) raw", "pp"], long=True,
        caption="E10 penalty form, quick run on 2 instances (\\texttt{results/E10\\_penalty\\_form/summary.csv}).",
        label="tab:app-e10"))

    # ---------------------------------------------------------------- E3 (median raw success, main text)
    piv = s3.pivot_table(index=["family", "n_vars"], columns="solver", values="p_success").reset_index()
    piv["fam"] = piv.family + " / " + piv.n_vars.astype(int).astype(str)
    piv = piv.sort_values(["family", "n_vars"], ascending=[False, True])
    cols = ["Greedy", "SA", "SA-matched", "SQA", "SQA-fixedT", "Tabu", "QAOA(p=4)"]
    write(OUT / "e3.tex", tabular(piv, ["fam"] + cols, ["family / vars"] + cols, align="l" + "r" * len(cols), d=2,
                                   size=r"\scriptsize"))
    # ---------------------------------------------------------------- E5 (main text)
    write(OUT / "e5.tex", tabular(s5, ["formulation", "solver", "n_vars", "p_success", "p_success_pp", "mean_benefit_ratio"],
                                   ["formulation", "solver", "vars", "P(opt) raw", "pp", "benefit"], align="llrrrr"))
    # ---------------------------------------------------------------- E9 (main text: alpha 0.01 and 1 plus references)
    s9m = s9[s9.alpha.isin(["0.01", "1", "--"])]
    write(OUT / "e9.tex", tabular(s9m, ["solver", "alpha", "p_feasible", "p_success", "p_success_pp", "mean_benefit_ratio_pp"],
                                   ["solver", "$\\alpha$", "P(feas)", "P(opt) raw", "P(opt) pp", "benefit pp"], align="llrrrr"))
    # ---------------------------------------------------------------- E10 (main text)
    write(OUT / "e10.tex", tabular(s10, ["form", "weight", "n_vars", "dynamic_range", "ground_feasible", "ground_is_optimum", "p_opt_pp"],
                                    ["form", "weight", "vars", "dyn.\\ range", "ground feas.", "ground opt.", "P(opt) pp"],
                                    align="llrrrrr", d={"dynamic_range": 1}))
    print("tables written to", OUT)


if __name__ == "__main__":
    main()
